
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Glickman
email: sammy.glickman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Believe it or not, Sam's site is not built.
  
  Please leave a message for me.
  
  I must be out, or this site would be awesome.
  
  Where could I be?
  
  Believe it or not, I'm working on updating!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  sglickman17

# Build settings
markdown: kramdown
